spring:
  profiles:
    active: '@spring.profiles.active@'
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oah6189vmK5UwCDb4x6
            client-secret: eaFG8AXC982sCcyn4g6egl0RdnUzxmuGqiPo83NC
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-542305.oktapreview.com/oauth2/default